### ISSUE TITLE
I want to add "Code-of-conduct" file

### ISSUE THREAD

**Issue by goodchai0** [Navaneethp007/MissionImpossible#18]
This will help contributor to know the rules and regulation for contributing.
Please assign this to me under hacktoberfest 2022. @Navaneethp007

**Comment by Navaneethp007** [comment]
Thanks for raising the issue. I have assigned it to you
Keep contributing!!!

**Comment by goodchai0** [comment]
Thank you for merging.  Please add "Hacktober-accepted" label, other wise it won't be counted. 
And close the issue.

**Comment by goodchai0** [comment]
Please add "Hacktober-accepted" label
