### ISSUE TITLE
I want to add  codechef and codeforces questions

### ISSUE THREAD

**Issue by satendragangwar** [Navaneethp007/MissionImpossible#24]
I want to add codechef and codeforces qustions .pls assign this to me.

**Comment by Navaneethp007** [comment]
You can add codechef solutions to the CodeChef folder...for the codeforces solution I will create a folder for that and then you can create solutions in it.
Keep Contributing!!!

**Comment by rajdeepdas2000** [comment]
I have submitted PR #19 . Kindly review it. Thanks.

**Comment by satendragangwar** [comment]
I have submitted PR pls review it

**Comment by Navaneethp007** [comment]
sure
